In [26]:
import pandas as pd
import json

In [30]:
table = pd.read_json('./static/data/lad_list_2021.json')

# Opening JSON file
with open('./static/data/lad_list_2021.json') as json_file:
    data = json.load(json_file)

# Opening JSON file
with open('./static/areareportsprgen.json') as json_file:
    reports = json.load(json_file)

In [31]:
table['standfirst'] = 'Stand'
for i in table.index:
    table['standfirst'][i] = reports[table['code'][i]]
table

,code,name,standfirst
0,E07000223,Adur,<! -- The population passed half a million--><...
1,E07000026,Allerdale,<! -- The population passed half a million--><...
2,E07000032,Amber Valley,<! -- The population passed half a million--><...
3,E07000224,Arun,<! -- The population passed half a million--><...
4,E07000170,Ashfield,<! -- The population passed half a million--><...
...,...,...,...
326,W06000006,Wrexham,<! -- The population passed half a million--><...
327,E07000238,Wychavon,<! -- The population passed half a million--><...
328,E07000128,Wyre,<! -- The population passed half a million--><...
329,E07000239,Wyre Forest,<! -- The population passed half a million--><...
330,E06000014,York,<! -- The population passed half a million--><...