In [14]:
import pandas as pd
import numpy as np
from random import randrange

In [15]:
## THIS IS NOT PART OF THE PIPELINE BUT CREATES SYNTHETIC 2021 DATA
## 
# Read data table
df = pd.read_csv('./ethnicity_2011.csv')

# For some reason some areas have an astrix in the title
df['Area Name'] = df['Area Name'].str.replace("*", "").str.strip() 

# CONVERT STRINGS TO INTEGERS

def convert_to_int(x):
    try:
        return int(x.replace(",", ""))
    except:
        try:
            return x.replace("â€™", "'")
        except:
            return x

df = df.applymap(convert_to_int)

# Create synthetic data in place of 2021 data
from random import random

def create_synth(x):
    if type(x) is int:
        num = random()+0.6
        return round(x * num)
    else:
        return x

dfsynth = df.applymap(create_synth)

In [16]:
dfsynth.to_csv('ethnicity_2021.csv', index = False)

In [17]:
dfempty = dfsynth[['Area Code','Area Name']]

In [18]:
care_df = dfempty.copy()
religion_df = dfempty.copy()
ethnicity_df = dfempty.copy()
health_df = dfempty.copy()
economic_df = dfempty.copy()
household_df = dfempty.copy()
marital_df = dfempty.copy()
hours_df = dfempty.copy()
tenure_df = dfempty.copy()
disability_df = dfempty.copy()
national_df = dfempty.copy()
welsh_df = dfempty.copy()
population_df = dfempty.copy()
density_df = dfempty.copy()
ageband_df = dfempty.copy()
agemed_df = dfempty.copy()
cob_df = dfempty.copy()

In [19]:
df_COBvars = pd.read_csv('./CountryOfBirthVars.csv')
df_COBvars = df_COBvars.drop(['Unnamed: 1'], axis=1)
cob_variables = [i for i in df_COBvars['Country of Birth']]

In [20]:
tables = {
    'population': {
        'table': 'population',
        'variables': [
            'Population'
        ]
    },
    'density': {
        'table': 'density',
        'variables': [
            'Density'
        ]
    },
    'marital': {
        'table': 'legal_partnership_status_6a',
        'variables': [
            'Never married and never registered a civil partnership',
            'Married or in a registered civil partnership',
            'Separated, but still legally married or still legally in a civil partnership',
            'Divorced or civil partnership dissolved',
            'Widowed or surviving civil partnership partner'
        ]
    },
    'household': {
        'table': 'hh_family_composition_8a',
        'variables': [
            'One person household: Aged 66 years and over',
            'One person household: Other',
            'Single family household: Couple family household: No children',
            'Single family household: Couple family household: Dependent children',
            'Single family household: Couple family household: All children non-dependent',
            'Single family household: Lone parent household',
            'Other household types'
        ]
    },
    'agemed': {
        'table': 'median_age',
        'variables': [
            'Median Age'
        ]
    },
    'ageband': {
        'table': 'resident_age_11a',
        'variables': [
            '0 - 4',
            '5 - 9',
            '10 - 15',
            '16 - 19',
            '20 - 24',
            '25 - 34',
            '35 - 49',
            '50 - 64',
            '65 - 74',
            '75 - 84',
            '85 - 115'
        ]
    },
    'cob': {
        'table': 'country_of_birth_25a',
        'variables': [
            'Europe: United Kingdom',
            'Europe: Ireland',
            'Europe: Other Europe: EU countries: Member countries in March 2001: France',
            'Europe: Other Europe: EU countries: Member countries in March 2001: Germany',
            'Europe: Other Europe: EU countries: Member countries in March 2001: Italy',
            'Europe: Other Europe: EU countries: Member countries in March 2001: Portugal (including Madeira and the Azores)',
            'Europe: Other Europe: EU countries: Member countries in March 2001: Other member countries in March 2001',
            'Europe: Other Europe: EU countries: Countries that joined the EU between April 2001 and March 2011: Poland',
            'Europe: Other Europe: EU countries: Countries that joined the EU between April 2001 and March 2011: Other EU  countries',
            'Europe: Other Europe: EU countries: Countries that joined the EU between April 2011 and March 2021: Croatia',
            'Europe: Other Europe: Rest of Europe',
            'Africa: Nigeria',
            'Africa: South Africa',
            'Africa: Other',
            'Middle East and Asia: China',
            'Middle East and Asia: Bangladesh',
            'Middle East and Asia: India',
            'Middle East and Asia: Pakistan',
            'Middle East and Asia: Other',
            'The Americas and the Caribbean: Canada',
            'The Americas and the Caribbean: United States',
            'The Americas and the Caribbean: Jamaica',
            'The Americas and the Caribbean: Other',
            'Antarctica, Oceania and other',
        ]
    },
    'ethnicity': {
        'table': 'ethnic_group_tb_6a',
        'variables': [
            'Asian, Asian British or Asian Welsh',
            'Black, Black British, Black Welsh, Caribbean or African',
            'Mixed or Multiple ethnic groups',
            'White',
            'Other ethnic group'
        ]
    },
    'national': {
        'table': 'national_identity_all_9a',
        'variables': [
            'British only identity',
            'Welsh only identity',
            'Welsh and British only identity',
            'English only identity',
            'English and British only identity',
            'Any other combination of only UK identities',
            'Non-UK identity only',
            'UK identity and non-UK identity'
        ]
    },
    'religion': {
        'table': 'religion_tb',
        'variables': [
            'No religion',
            'Christian',
            'Buddhist',
            'Hindu',
            'Jewish',
            'Muslim',
            'Sikh',
            'Other religion',
            'Not answered'
        ]
    },
    'welsh': {
        'table': 'welsh_skills_speak',
        'variables': [
            'Can speak Welsh',
            "Cannot speak Welsh"
        ]
        },
    'health': {
        'table': 'health_in_general_4a',
        'variables': [
            'Very good or good health',
            'Fair health',
            'Very bad or bad health'
        ]
        },
    'disability': {
        'table': 'disability_3a',
        'variables': [
            'Disabled under the Equality Act',
            'Not disabled under the Equality Act'
        ]
        },
    'care': {
        'table': 'is_carer_5a',
        'variables': [
            'Provides no unpaid care',
            'Provides 19 or less hours unpaid care a week',
            'Provides 20 to 49 hours unpaid care a week',
            'Provides 50 or more hours unpaid care a week'
        ]
        },
    'tenure': {
        'table': 'hh_tenure_7b',
        'variables': [
            'Owns outright or with a mortgage or loan',
            'Shared ownership',
            'Rented from council or Local Authority',
            'Other social rented',
            'Private rented',
            'Lives rent free'
        ]
    },
    'economic': {
        'table': 'economic_activity_status_7a',
        'variables': [
            'Economically active (including full-time students): In employment: Employee',
            'Economically active (including full-time students): In employment: Self-employed',
            'Economically active (including full-time students): Unemployed',
            'Economically inactive: Retired',
            'Economically inactive (including full-time students): Student',
            'Economically inactive: Looking after home or family',
            'Economically inactive: Long-term sick or disabled',
            'Economically inactive: Other'
        ]
    },
    'hours': {
        'table': 'Hours_Per_Week_Worked_5A',
        'variables': [
            'Part-time: 15 hours or less worked',
            'Part-time: 16 to 30 hours worked',
            'Full-time: 31 to 48 hours worked',
            'Full-time: 49 or more hours worked'
        ]
    }
}
tables['ageband']['variables'].reverse()

In [30]:
# population_variables = ['Population']
# density_variables = ['Density']
# # age10yr_variables = ['0-9', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80plus']
# new_age_band = ['0 - 4',
# '5 - 9',
# '10 - 15',
# '16 - 19',
# '20 - 24',
# '25 - 34',
# '35 - 49',
# '50 - 64',
# '65 - 74',
# '75 - 84',
# '85 - 115']
# agemed_variables = ['Median Age']
# welsh_variables = ['Can speak Welsh', "Cannot speak Welsh"]
# care_variables = ['Provides no unpaid care',
# 'Provides 19 or less hours unpaid care a week',
# 'Provides 20 to 49 hours unpaid care a week',
# 'Provides 50 or more hours unpaid care a week']
# religion_variables = ['No religion',
# 'Christian',
# 'Buddhist',
# 'Hindu',
# 'Jewish',
# 'Muslim',
# 'Sikh',
# 'Other religion',
# 'Not answered']

# ethnicity_variables = ['Asian, Asian British or Asian Welsh',
# 'Black, Black British, Black Welsh, Caribbean or African',
# 'Mixed or Multiple ethnic groups',
# 'White',
# 'Other ethnic group']
# health_variables = ['Very good or good health',
# 'Fair health',
# 'Very bad or bad health']
# economic_variables = ['Economically active (excluding full-time students): In employment',
# 'Economically active (excluding full-time students): Unemployed',
# 'Economically active and a full-time student: In employment',
# 'Economically active and a full-time student: Unemployed',
# 'Economically inactive (excluding full-time students)',
# 'Economically inactive and a full-time student']

# household_variables = ['One person household: Aged 66 years and over',
# 'One person household: Other',
# 'Single family household: All aged 66 years and over',
# 'Single family household: Married or civil partnership couple: No children',
# 'Single family household: Married or civil partnership couple: Dependent children',
# 'Single family household: Married or civil partnership couple: All children non-dependent',
# 'Single family household: Cohabiting couple family : No children',
# 'Single family household: Cohabiting couple family : With dependent children',
# 'Single family household: Cohabiting couple family : All children non-dependent',
# 'Single family household: Lone parent family : With dependent children',
# 'Single family household: Lone parent family : All children non-dependent',
# 'Single family household: Other single family household: Other family composition',
# 'Multiple-family household: With dependent children',
# 'Multiple-Family Household : Other, including all full-time students and all aged 66 years and over']

# #  Change household to HH_FAMILY_COMPOSITION_8A
# marital_variables = [
# 'Never married and never registered a civil partnership',
# 'Married or in a registered civil partnership',
# 'Separated, but still legally married or still legally in a civil partnership',
# 'Divorced or civil partnership dissolved',
# 'Widowed or surviving civil partnership partner'
# ]
# hours_variables = [
# 'Part-time: 15 hours or less worked',
# 'Part-time: 16 to 30 hours worked',
# 'Full-time: 31 to 48 hours worked',
# 'Full-time: 49 or more hours worked'
# ]
# tenure_variables = [
# 'Owns outright or with a mortgage or loan',
# 'Shared ownership',
# 'Rented from council or Local Authority',
# 'Other social rented',
# 'Private rented',
# 'Lives rent free'
# ]
# disability_variables = [
# 'Disabled under the Equality Act',
# 'Not disabled under the Equality Act'
# ]
# national_variables = [
# 'British only identity',
# 'Welsh only identity',
# 'Welsh and British only identity',
# 'English only identity',
# 'English and British only identity',
# 'Any other combination of only UK identities',
# 'Non-UK identity only',
# 'UK identity and non-UK identity'
# ]

In [31]:
vars_df = [
    {'vars': tables['care']['variables'], 'df': care_df, 'name': 'care'},
    {'vars': tables['religion']['variables'], 'df': religion_df, 'name': 'religion'},
    {'vars': tables['ethnicity']['variables'], 'df': ethnicity_df, 'name':'ethnicity'},
    {'vars': tables['health']['variables'], 'df': health_df, 'name': 'health'},
    {'vars': tables['economic']['variables'], 'df': economic_df, 'name': 'economic'},
    {'vars': tables['household']['variables'], 'df': household_df, 'name': 'household'},
    {'vars': tables['marital']['variables'], 'df': marital_df, 'name': 'marital'},
    {'vars': tables['hours']['variables'], 'df': hours_df, 'name': 'hours'},
    {'vars': tables['tenure']['variables'], 'df': tenure_df, 'name': 'tenure'},
    {'vars': tables['disability']['variables'], 'df': disability_df, 'name': 'disability'},
    {'vars': tables['national']['variables'], 'df': national_df, 'name': 'national'},
    {'vars': tables['welsh']['variables'], 'df': welsh_df, 'name': 'welsh'},
    {'vars': tables['population']['variables'], 'df': population_df, 'name': 'population'},
    {'vars': tables['density']['variables'], 'df': density_df, 'name': 'density'},
    {'vars': tables['ageband']['variables'], 'df': ageband_df, 'name': 'ageband'},
    {'vars': tables['agemed']['variables'], 'df': agemed_df, 'name': 'agemed'},
    {'vars': tables['cob']['variables'], 'df': cob_df, 'name': 'cob'}
]

In [32]:
def rand_list(length, topic=None, var=None):
    r_list =[]
    for i in range(length):
        r_list.append(randrange(1000, 10000))

    print('topic', topic)
    if topic=='cob':
        print('var', var)
        if var=='Europe: United Kingdom':
            print('uk')
            r_list = [i*100 for i in r_list]
        if 'other' in var[-20:]:
            r_list = [i/10 for i in r_list]

    if topic=='density':
        r_list = [(randrange(2, 200)/2) for i in r_list]

    if topic=='agemed':
        r_list = [(randrange(40, 100)/2) for i in r_list]

    return r_list

In [33]:
for ob in vars_df:
    print('name', ob['name'])
    for var in ob['vars']:
        ob['df'][var] = rand_list(ob['df'].shape[0], ob['name'], var)
        dfsynth = ob['df'].applymap(create_synth)
        ob['df'].to_csv(ob['name']+'_2011.csv', index = False)
        dfsynth.to_csv(ob['name']+'_2021.csv', index = False)

name care
topic care
topic care
topic care
topic care
name religion
topic religion
topic religion
topic religion
topic religion
topic religion
topic religion
topic religion
topic religion
topic religion
name ethnicity
topic ethnicity
topic ethnicity
topic ethnicity
topic ethnicity
topic ethnicity
name health
topic health
topic health
topic health
name economic
topic economic
topic economic
topic economic
topic economic
topic economic
topic economic
topic economic
topic economic
name household
topic household
topic household
topic household
topic household
topic household
topic household
topic household
name marital
topic marital
topic marital
topic marital
topic marital
topic marital
name hours
topic hours
topic hours
topic hours
topic hours
name tenure
topic tenure
topic tenure
topic tenure
topic tenure
topic tenure
topic tenure
name disability
topic disability
topic disability
name national
topic national
topic national
topic national
topic national
topic national
topic national
topic national
topic national
name welsh
topic welsh
topic welsh
name population
topic population
name density
topic density
name ageband
topic ageband
topic ageband
topic ageband
topic ageband
topic ageband
topic ageband
topic ageband
topic ageband
topic ageband
topic ageband
topic ageband
name agemed
topic agemed
name cob
topic cob
var Europe: United Kingdom
uk
topic cob
var Europe: Ireland
topic cob
var Europe: Other Europe: EU countries: Member countries in March 2001: France
topic cob
var Europe: Other Europe: EU countries: Member countries in March 2001: Germany
topic cob
var Europe: Other Europe: EU countries: Member countries in March 2001: Italy
topic cob
var Europe: Other Europe: EU countries: Member countries in March 2001: Portugal (including Madeira and the Azores)
topic cob
var Europe: Other Europe: EU countries: Member countries in March 2001: Other member countries in March 2001
topic cob
var Europe: Other Europe: EU countries: Countries that joined the EU between April 2001 and March 2011: Poland
topic cob
var Europe: Other Europe: EU countries: Countries that joined the EU between April 2001 and March 2011: Other EU  countries
topic cob
var Europe: Other Europe: EU countries: Countries that joined the EU between April 2011 and March 2021: Croatia
topic cob
var Europe: Other Europe: Rest of Europe
topic cob
var Africa: Nigeria
topic cob
var Africa: South Africa
topic cob
var Africa: Other
topic cob
var Middle East and Asia: China
topic cob
var Middle East and Asia: Bangladesh
topic cob
var Middle East and Asia: India
topic cob
var Middle East and Asia: Pakistan
topic cob
var Middle East and Asia: Other
topic cob
var The Americas and the Caribbean: Canada
topic cob
var The Americas and the Caribbean: United States
topic cob
var The Americas and the Caribbean: Jamaica
topic cob
var The Americas and the Caribbean: Other
topic cob
var Antarctica, Oceania and other

In [108]:
national_df

,Area Code,Area Name,British only identity,Welsh only identity,Welsh and British only identity,English only identity,English and British only identity,Any other combination of only UK identities,Non-UK identity only,UK identity and non-UK identity
0,K04000001,ENGLAND AND WALES,68416,27946,71651,41551,33671,52418,46971,74395
1,E92000001,ENGLAND,32782,88031,53698,57387,52629,42148,69719,50790
2,E12000001,NORTH EAST,43981,36784,70685,46963,69449,27503,12084,9991
3,E06000047,County Durham,33520,69192,17343,6757,29382,78428,19346,42880
4,E06000005,Darlington,79881,73938,88079,52553,99496,18783,88630,89426
...,...,...,...,...,...,...,...,...,...,...
370,W06000018,Caerphilly,19036,86430,52335,11412,75273,82202,4565,37712
371,W06000019,Blaenau Gwent,67246,94494,98327,80164,90766,28250,67405,34300
372,W06000020,Torfaen,43704,21788,11927,60478,42535,42584,66661,33875
373,W06000021,Monmouthshire,35938,91950,2598,88662,75633,77225,21194,95156
374,W06000022,Newport,55392,14706,75122,18480,92345,86998,62745,46417

In [53]:
# Create hierarchy lookups
lacountydistcountry = pd.read_csv('./csv/lists/Ward_to_Local_Authority_District_to_County_to_Region_to_Country_(December_2021)_Lookup_in_United_Kingdom.csv')
lacountydistcountry = lacountydistcountry[['LAD21CD', 'LAD21NM', 'CTY21CD', 'CTY21NM', 'RGN21CD', 'RGN21NM', 'CTRY21CD', 'CTRY21NM']]

lacountydistcountry = lacountydistcountry[lacountydistcountry['LAD21CD'].apply(lambda x: x[0] not in ['S', 'N'])]

lacountydistcountry = lacountydistcountry.drop_duplicates()

for i in lacountydistcountry.index:
    # Check if nan
    if lacountydistcountry.loc[i]['CTY21CD'] != lacountydistcountry.loc[i]['CTY21CD']:
        lacountydistcountry.loc[i]['CTY21CD'] = lacountydistcountry.loc[i]['LAD21CD']
        lacountydistcountry.loc[i]['CTY21NM'] = lacountydistcountry.loc[i]['LAD21NM']

    if lacountydistcountry.loc[i]['RGN21CD'] != lacountydistcountry.loc[i]['RGN21CD']:
        lacountydistcountry.loc[i]['RGN21CD'] = lacountydistcountry.loc[i]['CTRY21CD']
        lacountydistcountry.loc[i]['RGN21NM'] = lacountydistcountry.loc[i]['CTRY21NM']

lacountydistcountry.to_csv('LAD_County_Region_Country_2021.csv', index = False)

In [54]:
for ob in vars_df:
    for var in ob['vars']:
        ob['df'][var] = rand_list(ob['df'].shape[0])
        dfsynth = ob['df'].applymap(create_synth)
        ob['df'].to_csv(ob['name']+'_2011.csv', index = False)
        dfsynth.to_csv(ob['name']+'_2021.csv', index = False)

topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None
topic None

In [55]:
{i: [i] for i in cob_variables}

{'Elsewhere': ['Elsewhere'],
 'Afghanistan': ['Afghanistan'],
 'Albania': ['Albania'],
 'Antarctica': ['Antarctica'],
 'Algeria': ['Algeria'],
 'American Samoa': ['American Samoa'],
 'Andorra': ['Andorra'],
 'Angola': ['Angola'],
 'Antigua and Barbuda': ['Antigua and Barbuda'],
 'Azerbaijan': ['Azerbaijan'],
 'Argentina': ['Argentina'],
 'Australia': ['Australia'],
 'Austria': ['Austria'],
 'Bahamas, The': ['Bahamas, The'],
 'Bahrain': ['Bahrain'],
 'Bangladesh': ['Bangladesh'],
 'Armenia': ['Armenia'],
 'Barbados': ['Barbados'],
 'Belgium': ['Belgium'],
 'Bermuda': ['Bermuda'],
 'Bhutan': ['Bhutan'],
 'Bolivia': ['Bolivia'],
 'Bosnia and Herzegovina': ['Bosnia and Herzegovina'],
 'Botswana': ['Botswana'],
 'Bouvet Island': ['Bouvet Island'],
 'Brazil': ['Brazil'],
 'Belize': ['Belize'],
 'British Indian Ocean Territory': ['British Indian Ocean Territory'],
 'Solomon Islands': ['Solomon Islands'],
 'British Virgin Islands': ['British Virgin Islands'],
 'Brunei': ['Brunei'],
 'Bulgaria': ['Bulgaria'],
 'Myanmar (Burma)': ['Myanmar (Burma)'],
 'Burundi': ['Burundi'],
 'Belarus': ['Belarus'],
 'Cambodia': ['Cambodia'],
 'Cameroon': ['Cameroon'],
 'Canada': ['Canada'],
 'Cape Verde': ['Cape Verde'],
 'Cayman Islands': ['Cayman Islands'],
 'Central African Republic': ['Central African Republic'],
 'Sri Lanka': ['Sri Lanka'],
 'Chad': ['Chad'],
 'Chile': ['Chile'],
 'China': ['China'],
 'Taiwan': ['Taiwan'],
 'Christmas Island': ['Christmas Island'],
 'Cocos (Keeling) Islands': ['Cocos (Keeling) Islands'],
 'Colombia': ['Colombia'],
 'Comoros': ['Comoros'],
 'Mayotte': ['Mayotte'],
 'Congo': ['Congo'],
 'Congo (Democratic Republic)': ['Congo (Democratic Republic)'],
 'Cook Islands': ['Cook Islands'],
 'Costa Rica': ['Costa Rica'],
 'Croatia': ['Croatia'],
 'Cuba': ['Cuba'],
 'Czechia': ['Czechia'],
 'Benin': ['Benin'],
 'Denmark': ['Denmark'],
 'Dominica': ['Dominica'],
 'Dominican Republic': ['Dominican Republic'],
 'Ecuador': ['Ecuador'],
 'El Salvador': ['El Salvador'],
 'Equatorial Guinea': ['Equatorial Guinea'],
 'Ethiopia': ['Ethiopia'],
 'Eritrea': ['Eritrea'],
 'Estonia': ['Estonia'],
 'Faroe Islands': ['Faroe Islands'],
 'Falkland Islands': ['Falkland Islands'],
 'South Georgia and the South Sandwich Islands': ['South Georgia and the South Sandwich Islands'],
 'Fiji': ['Fiji'],
 'Finland': ['Finland'],
 'Ã…land Islands': ['Ã…land Islands'],
 'France': ['France'],
 'French Guiana': ['French Guiana'],
 'French Polynesia': ['French Polynesia'],
 'French Southern Territories': ['French Southern Territories'],
 'Djibouti': ['Djibouti'],
 'Gabon': ['Gabon'],
 'Georgia': ['Georgia'],
 'Gambia, The': ['Gambia, The'],
 'Occupied Palestinian Territories': ['Occupied Palestinian Territories'],
 'Germany': ['Germany'],
 'Ghana': ['Ghana'],
 'Gibraltar': ['Gibraltar'],
 'Kiribati': ['Kiribati'],
 'Greece': ['Greece'],
 'Greenland': ['Greenland'],
 'Grenada': ['Grenada'],
 'Guadeloupe': ['Guadeloupe'],
 'Guam': ['Guam'],
 'Guatemala': ['Guatemala'],
 'Guinea': ['Guinea'],
 'Guyana': ['Guyana'],
 'Haiti': ['Haiti'],
 'Heard Island and McDonald Islands': ['Heard Island and McDonald Islands'],
 'Vatican City': ['Vatican City'],
 'Honduras': ['Honduras'],
 'Hong Kong (Special administrative region of China)': ['Hong Kong (Special administrative region of China)'],
 'Hungary': ['Hungary'],
 'Iceland': ['Iceland'],
 'India': ['India'],
 'Indonesia': ['Indonesia'],
 'Iran': ['Iran'],
 'Iraq': ['Iraq'],
 'Ireland': ['Ireland'],
 'Island of Ireland (Not otherwise specified)': ['Island of Ireland (Not otherwise specified)'],
 'Israel': ['Israel'],
 'Italy': ['Italy'],
 'Ivory Coast': ['Ivory Coast'],
 'Jamaica': ['Jamaica'],
 'Japan': ['Japan'],
 'Kazakhstan': ['Kazakhstan'],
 'Jordan': ['Jordan'],
 'Kenya': ['Kenya'],
 'Korea (North)': ['Korea (North)'],
 'Korea (South)': ['Korea (South)'],
 'Kuwait': ['Kuwait'],
 'Kyrgyzstan': ['Kyrgyzstan'],
 'Laos': ['Laos'],
 'Lebanon': ['Lebanon'],
 'Lesotho': ['Lesotho'],
 'Latvia': ['Latvia'],
 'Liberia': ['Liberia'],
 'Libya': ['Libya'],
 'Liechtenstein': ['Liechtenstein'],
 'Lithuania': ['Lithuania'],
 'Luxembourg': ['Luxembourg'],
 'Macao (Special administrative region of China)': ['Macao (Special administrative region of China)'],
 'Madagascar': ['Madagascar'],
 'Malawi': ['Malawi'],
 'Malaysia': ['Malaysia'],
 'Maldives': ['Maldives'],
 'Mali': ['Mali'],
 'Malta': ['Malta'],
 'Martinique': ['Martinique'],
 'Mauritania': ['Mauritania'],
 'Mauritius': ['Mauritius'],
 'Mexico': ['Mexico'],
 'Monaco': ['Monaco'],
 'Mongolia': ['Mongolia'],
 'Moldova': ['Moldova'],
 'Montenegro': ['Montenegro'],
 'Montserrat': ['Montserrat'],
 'Morocco': ['Morocco'],
 'Mozambique': ['Mozambique'],
 'Oman': ['Oman'],
 'Namibia': ['Namibia'],
 'Nauru': ['Nauru'],
 'Nepal': ['Nepal'],
 'Netherlands': ['Netherlands'],
 'Curacao': ['Curacao'],
 'Aruba': ['Aruba'],
 'Sint Maarten (Dutch Part)': ['Sint Maarten (Dutch Part)'],
 'Bonaire, Sint Eustatius and Saba': ['Bonaire, Sint Eustatius and Saba'],
 'New Caledonia': ['New Caledonia'],
 'Vanuatu': ['Vanuatu'],
 'New Zealand': ['New Zealand'],
 'Nicaragua': ['Nicaragua'],
 'Niger': ['Niger'],
 'Nigeria': ['Nigeria'],
 'Niue': ['Niue'],
 'Norfolk Island': ['Norfolk Island'],
 'Norway': ['Norway'],
 'Northern Mariana Islands': ['Northern Mariana Islands'],
 'United States minor outlying islands': ['United States minor outlying islands'],
 'Micronesia': ['Micronesia'],
 'Marshall Islands': ['Marshall Islands'],
 'Palau': ['Palau'],
 'Pakistan': ['Pakistan'],
 'Panama': ['Panama'],
 'Papua New Guinea': ['Papua New Guinea'],
 'Paraguay': ['Paraguay'],
 'Peru': ['Peru'],
 'Philippines': ['Philippines'],
 'Pitcairn, Henderson, Ducie and Oeno Islands': ['Pitcairn, Henderson, Ducie and Oeno Islands'],
 'Poland': ['Poland'],
 'Portugal': ['Portugal'],
 'Guinea-Bissau': ['Guinea-Bissau'],
 'East Timor': ['East Timor'],
 'Puerto Rico': ['Puerto Rico'],
 'Qatar': ['Qatar'],
 'RÃ©union': ['RÃ©union'],
 'Romania': ['Romania'],
 'Russia': ['Russia'],
 'Rwanda': ['Rwanda'],
 'St BarthÃ©lemy': ['St BarthÃ©lemy'],
 'St Helena, Ascension and Tristan da Cunha': ['St Helena, Ascension and Tristan da Cunha'],
 'St Kitts and Nevis': ['St Kitts and Nevis'],
 'Anguilla': ['Anguilla'],
 'St Lucia': ['St Lucia'],
 'St Martin (French part)': ['St Martin (French part)'],
 'St Pierre and Miquelon': ['St Pierre and Miquelon'],
 'St Vincent and the Grenadines': ['St Vincent and the Grenadines'],
 'San Marino': ['San Marino'],
 'Sao Tome and Principe': ['Sao Tome and Principe'],
 'Saudi Arabia': ['Saudi Arabia'],
 'Senegal': ['Senegal'],
 'Serbia': ['Serbia'],
 'Seychelles': ['Seychelles'],
 'Sierra Leone': ['Sierra Leone'],
 'Singapore': ['Singapore'],
 'Slovakia': ['Slovakia'],
 'Vietnam': ['Vietnam'],
 'Slovenia': ['Slovenia'],
 'Somalia': ['Somalia'],
 'South Africa': ['South Africa'],
 'Zimbabwe': ['Zimbabwe'],
 'South Sudan': ['South Sudan'],
 'Sudan': ['Sudan'],
 'Western Sahara': ['Western Sahara'],
 'Suriname': ['Suriname'],
 'Svalbard and Jan Mayen': ['Svalbard and Jan Mayen'],
 'Eswatini': ['Eswatini'],
 'Sweden': ['Sweden'],
 'Switzerland': ['Switzerland'],
 'Syria': ['Syria'],
 'Tajikistan': ['Tajikistan'],
 'Thailand': ['Thailand'],
 'Togo': ['Togo'],
 'Tokelau': ['Tokelau'],
 'Tonga': ['Tonga'],
 'Trinidad and Tobago': ['Trinidad and Tobago'],
 'United Arab Emirates': ['United Arab Emirates'],
 'Tunisia': ['Tunisia'],
 'Turkey': ['Turkey'],
 'Turkmenistan': ['Turkmenistan'],
 'Turks and Caicos Islands': ['Turks and Caicos Islands'],
 'Tuvalu': ['Tuvalu'],
 'Uganda': ['Uganda'],
 'Ukraine': ['Ukraine'],
 'Macedonia': ['Macedonia'],
 'Egypt': ['Egypt'],
 'Guernsey': ['Guernsey'],
 'Jersey': ['Jersey'],
 'Isle of Man': ['Isle of Man'],
 'Tanzania': ['Tanzania'],
 'United States': ['United States'],
 'United States Virgin Islands': ['United States Virgin Islands'],
 'Burkina Faso': ['Burkina Faso'],
 'Uruguay': ['Uruguay'],
 'Uzbekistan': ['Uzbekistan'],
 'Venezuela': ['Venezuela'],
 'Wallis and Futuna': ['Wallis and Futuna'],
 'Samoa': ['Samoa'],
 'Yemen': ['Yemen'],
 'Zambia': ['Zambia'],
 'Cyprus (European Union)': ['Cyprus (European Union)'],
 'Cyprus (Non-European Union)': ['Cyprus (Non-European Union)'],
 'Cyprus (Not otherwise specified)': ['Cyprus (Not otherwise specified)'],
 'Spain (Except Canary Islands)': ['Spain (Except Canary Islands)'],
 'Canary Islands': ['Canary Islands'],
 'Spain (Not otherwise specified)': ['Spain (Not otherwise specified)'],
 'England': ['England'],
 'Northern Ireland': ['Northern Ireland'],
 'Scotland': ['Scotland'],
 'Wales': ['Wales'],
 'Great Britain (Not otherwise specified)': ['Great Britain (Not otherwise specified)'],
 'United Kingdom (Not otherwise specified)': ['United Kingdom (Not otherwise specified)'],
 'Channel Islands (Not otherwise specified)': ['Channel Islands (Not otherwise specified)'],
 'Kosovo': ['Kosovo'],
 'Czechoslovakia (Not otherwise specified)': ['Czechoslovakia (Not otherwise specified)'],
 'Union of Soviet Socialist Republics (Not otherwise specified)': ['Union of Soviet Socialist Republics (Not otherwise specified)'],
 'Yugoslavia (Not otherwise specified)': ['Yugoslavia (Not otherwise specified)'],
 'Serbia and Montenegro (Not otherwise specified)': ['Serbia and Montenegro (Not otherwise specified)'],
 'Europe (Not otherwise specified)': ['Europe (Not otherwise specified)'],
 'Africa (Not otherwise specified)': ['Africa (Not otherwise specified)'],
 'Middle East (Not otherwise specified)': ['Middle East (Not otherwise specified)'],
 'Asia (Except Middle East) (Not otherwise specified)': ['Asia (Except Middle East) (Not otherwise specified)'],
 'North America (Not otherwise specified)': ['North America (Not otherwise specified)'],
 'Central America (Not otherwise specified)': ['Central America (Not otherwise specified)'],
 'South America (Not otherwise specified)': ['South America (Not otherwise specified)'],
 'Caribbean (Not otherwise specified)': ['Caribbean (Not otherwise specified)'],
 'Antarctica and Oceania (Not otherwise specified)': ['Antarctica and Oceania (Not otherwise specified)'],
 'At sea': ['At sea'],
 'In the air': ['In the air'],
 'Netherlands Antilles (Not otherwise specified)': ['Netherlands Antilles (Not otherwise specified)']}

In [32]:
# population_variables = ['Population']
# density_variables = ['Density']
# age10yr_variables = ['0-9', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80plus']
# agemed_variables = ['Median Age']
# welsh_variables = ['Speaks Welsh', "Doesn't speak Welsh"]
# care_variables = ['Not a carer', 'Yes, 9 hours a week or less', 'Yes, 10 to 19 hours a week', 'Yes, 20 to 34 hours a week', 'Yes, 35 to 49 hours a week', 'Yes, 50 or more hours a week']
# religion_variables = ['No religion',
# 'Christian',
# 'Buddhist',
# 'Hindu',
# 'Jewish',
# 'Muslim',
# 'Sikh',
# 'Other religion',
# 'Not stated']
# ethnicity_variables = ['Asian, Asian British or Asian Welsh',
# 'Black, Black British, Black Welsh, Carribean or African',
# 'Mixed or Multiple ethnic groups',
# 'White',
# 'Other ethnic group']
# health_variables = ['Very good health',
# 'Good health',
# 'Fair health',
# 'Bad health',
# 'Very bad health',]
# economic_variables = ['Economically active (excluding full-time students): In employment: Employee: Part-time',
# 'Economically active (excluding full-time students): In employment: Employee: Full-time',
# 'Economically active (excluding full-time students): In employment: Self-employed: Part-time',
# 'Economically active (excluding full-time students): In employment: Self-employed: Full-time',
# 'Economically active: Unemployed: Not a full-time student',
# 'Economically active: Full-time student',
# 'Economically inactive: Retired',
# 'Economically inactive (including full-time students): Student',
# 'Economically inactive: Looking after home or family',
# 'Economically inactive: Long-term sick or disabled',
# 'Economically inactive: Other']
# household_variables = ['One person household: Aged 66 years and over',
# 'One person household: Other',
# 'Single family household: All aged 66 years and over',
# 'Single family household: Married or civil partnership couple: No children',
# 'Single family household: Married or civil partnership couple: Dependent children',
# 'Single family household: Married or civil partnership couple: All children non-dependent',
# 'Single family household: Cohabiting couple family : No children',
# 'Single family household: Cohabiting couple family : With dependent children',
# 'Single family household: Cohabiting couple family : All children non-dependent',
# 'Single family household: Lone parent family : With dependent children',
# 'Single family household: Lone parent family : All children non-dependent',
# 'Single family household: Other single family household: Other family composition',
# 'Multiple-family household: With dependent children',
# 'Multiple-Family Household : Other, including all full-time students and all aged 66 years and over']
# marital_variables = ['Single never married or in a civil partnership',
# 'Married or in a registered civil partnership',
# 'Separated (but still legally married or still legally in a civil partnership)',
# 'Divorced or civil partnership dissolved',
# 'Widowed or surviving civil partnership partner' ]
# hours_variables = ['Part-time: 15 hours or less worked',
# 'Part-time: 16 to 30 hours worked',
# 'Full-time: 31 to 48 hours worked',
# 'Full-time: 49 or more hours worked']
# tenure_variables = ['Owned: Owns outright',
# 'Owned: Owns with a mortgage or loan',
# 'Shared ownership: Shared ownership',
# 'Social rented: Rents from council or Local Authority',
# 'Social rented: Other social rented',
# 'Private rented: Private landlord or letting agency',
# 'Private rented: Other private rented',
# 'Lives rent free']
# disability_variables = ['Disabled under the Equality Act: Day-to-day activities limited a lot',
# 'Disabled under the Equality Act: Day-to-day activities limited a little',
# 'Not disabled under the Equality Act :Has long term physical or mental health condition but day-to-day activities are not limited',
# 'Not disabled under the Equality Act: No long term physical or mental health conditions']
# national_variables = ['British only identity',
# 'English only identity',
# 'English and British only identity',
# 'Welsh only identity',
# 'Welsh and British only identity',
# 'Scottish only identity',
# 'Scottish and British only identity',
# 'Northern Irish only identity',
# 'Northern Irish and British only identity',
# 'Cornish only identity',
# 'Cornish and British only identity',
# 'Any other combination of UK identities (UK only)',
# 'Irish only identity',
# 'Irish and at least one UK identity',
# 'Other identity only',
# 'Other identity and at least one UK identity']